// Hand-curated from a real Overpass API export of ABU Zaria (Main Campus).
// Source: OpenStreetMap contributors, exported via overpass-turbo.eu, 2026-07-02.
// Cleaned: duplicates merged (Senate Building x3 -> 1, Sick Bay x2 -> 1,
// Akenzua Hall x10 -> 1), junk/off-scope entries removed, obvious OSM typos
// corrected. Kongo Campus is not represented — OSM has no tagged features
// there yet; add those manually after a Google Maps coordinate lookup.

import type { categoryEnum } from "@/db/schema/locations";

type LocationCategory = (typeof categoryEnum.enumValues)[number];

export type LocationSeed = {
  name: string;
  category: LocationCategory;
  description: string | null;
  address: string | null;
  latitude: number;
  longitude: number;
};

const MAIN_CAMPUS_ADDRESS = "ABU Main Campus, Samaru, Zaria, Kaduna State";
const AHMADU_BELLO_CAMPUS_ADDRESS = "Ahmadu Bello Campus, Samaru, Zaria, Kaduna State";

export const abuLocations: LocationSeed[] = [
  {
    name: "Senate Building",
    category: "administrative",
    description:
      "Central administrative building housing the Vice-Chancellor's office and university registry.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150642,
    longitude: 7.654551,
  },
  {
    name: "BBC World Service Trust - Ahmadu Bello University Radio Studio",
    category: "other",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.153725,
    longitude: 7.650079,
  },
  {
    name: "BlueRoof",
    category: "recreation",
    description: "Pope John Paul Multi-purpose Hall.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.154149,
    longitude: 7.653823,
  },
  {
    name: "ABU Zaria Bookshop",
    category: "other",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150910,
    longitude: 7.655885,
  },
  {
    name: "Department of Chemical Engineering",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149940,
    longitude: 7.651706,
  },
  {
    name: "Institute of Education",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149330,
    longitude: 7.652530,
  },
  {
    name: "CISCO",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149770,
    longitude: 7.654452,
  },
  {
    name: "Department of Geology",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149603,
    longitude: 7.653561,
  },
  {
    name: "Department of Physics",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149981,
    longitude: 7.653144,
  },
  {
    name: "Department of Geography",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149938,
    longitude: 7.653998,
  },
  {
    name: "Department of Mathematics",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150429,
    longitude: 7.653556,
  },
  {
    name: "Faculty of Arts",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149581,
    longitude: 7.654211,
  },
  {
    name: "Department of Biology",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150940,
    longitude: 7.653158,
  },
  {
    name: "Department of Biochemistry",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.149651,
    longitude: 7.652027,
  },
  {
    name: "Department of Urban & Regional Planning",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.151318,
    longitude: 7.650365,
  },
  {
    name: "Department of Industrial Design",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150762,
    longitude: 7.650838,
  },
  {
    name: "Department of Building",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.151323,
    longitude: 7.650814,
  },
  {
    name: "Theatre CD",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.151123,
    longitude: 7.650194,
  },
  {
    name: "Sculpture Garden",
    category: "recreation",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150237,
    longitude: 7.651240,
  },
  {
    name: "FSLT Lecture Theatre",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150439,
    longitude: 7.653016,
  },
  {
    name: "ABU Zaria Sick Bay",
    category: "health",
    description: "Campus medical emergency and first-aid facility.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.154674,
    longitude: 7.651974,
  },
  {
    name: "Basket Ball Court",
    category: "recreation",
    description: "Outdoor basketball court.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.151816,
    longitude: 7.655497,
  },
  {
    name: "Guidance and Counselling Unit",
    category: "administrative",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.152465,
    longitude: 7.655888,
  },
  {
    name: "Pepsi Garden",
    category: "recreation",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.153101,
    longitude: 7.654922,
  },
  {
    name: "Chapel of Redemption",
    category: "worship",
    description: null,
    address: AHMADU_BELLO_CAMPUS_ADDRESS,
    latitude: 11.153655,
    longitude: 7.654211,
  },
  {
    name: "Aniki Super",
    category: "food",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.157261,
    longitude: 7.650110,
  },
  {
    name: "ABU Institute Library",
    category: "academic",
    description: "For research students.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.151204,
    longitude: 7.655023,
  },
  {
    name: "Geography Department Mosque",
    category: "worship",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.150134,
    longitude: 7.653994,
  },
  {
    name: "Demonstration Secondary School",
    category: "academic",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.155304,
    longitude: 7.653849,
  },
  {
    name: "Postgraduate Block (F0)",
    category: "accommodation",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.154107,
    longitude: 7.652727,
  },
  {
    name: "Suleiman Masjid",
    category: "worship",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.154950,
    longitude: 7.652876,
  },
  {
    name: "Akenzua Hall",
    category: "accommodation",
    description: "Student hostel complex (merged from multiple mapped building blocks).",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.153879,
    longitude: 7.659802,
  },
  {
    name: "Samaru Mosque",
    category: "worship",
    description: null,
    address: "Samaru, Zaria, Kaduna State",
    latitude: 11.161350,
    longitude: 7.646702,
  },
  {
    name: "MRS Fuel Station",
    category: "transport",
    description: "Fuel station.",
    address: "Samaru, Zaria, Kaduna State",
    latitude: 11.160812,
    longitude: 7.647482,
  },
  {
    name: "Ahmadu Bello University Teaching Hospital (Samaru)",
    category: "health",
    description: null,
    address: "Samaru, Zaria, Kaduna State",
    latitude: 11.174072,
    longitude: 7.605154,
  },
  {
    name: "Ahmadu Bello Campus Fire Station",
    category: "security",
    description: "Campus fire and emergency response station.",
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.154199,
    longitude: 7.650456,
  },
  {
    name: "Central Mosque",
    category: "worship",
    description: null,
    address: AHMADU_BELLO_CAMPUS_ADDRESS,
    latitude: 11.153691,
    longitude: 7.656759,
  },
  {
    name: "F C M B",
    category: "other",
    description: "Bank branch with ATM services.",
    address: AHMADU_BELLO_CAMPUS_ADDRESS,
    latitude: 11.154261,
    longitude: 7.657346,
  },
  {
    name: "Geography Dept Medical Center",
    category: "health",
    description: null,
    address: MAIN_CAMPUS_ADDRESS,
    latitude: 11.152862,
    longitude: 7.648494,
  },
] satisfies LocationSeed[];